title: "Rajesh Karra"
author: "Rajesh kumar Karra"
description: "Osmania University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header
show_social: ture         # show site description and social links in the footer
mathjax: true
ORCID: "0000-0003-4099-7143"
search_enabled: true
heading_anchors: true
# Menu

favicon_ico: "/assets/images/favicon.ico"





navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV", url: "https://docs.google.com/document/d/1rNrB22x_txxA18JJygJHB-Au_DLogMFYL0yeXYe6ZjE/edit?usp=sharing" }
  - {title: "Essentials", file: "essentials.md"}
  - {title: "Spotlights", file: "spotlights.md"}
  - {title: "Gists", file: "gists.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:rajeshkumarkarra@outlook.com"}
  - {title: Github, icon: github, url: "https://github.com/rajeshkumarkarra"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/k_rajesh_kumar"}
  - {title: ORCID, icon: orcid, url: "https://orcid.org/0000-0003-4099-7143"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
